CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Duenos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "Apellido" character varying(100) NOT NULL,
    "Telefono" character varying(20) NOT NULL,
    "Direccion" character varying(200) NOT NULL,
    "Correo" character varying(100) NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Duenos" PRIMARY KEY ("Id")
);

CREATE TABLE "Especies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(50) NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Especies" PRIMARY KEY ("Id")
);

CREATE TABLE "Veterinarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "Apellido" character varying(100) NOT NULL,
    "Especialidad" character varying(100) NOT NULL,
    "Telefono" character varying(20) NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Veterinarios" PRIMARY KEY ("Id")
);

CREATE TABLE "Mascotas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "FechaNacimiento" timestamp with time zone NOT NULL,
    "Peso" numeric NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "DuenoId" integer NOT NULL,
    "EspecieId" integer NOT NULL,
    CONSTRAINT "PK_Mascotas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Mascotas_Duenos_DuenoId" FOREIGN KEY ("DuenoId") REFERENCES "Duenos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Mascotas_Especies_EspecieId" FOREIGN KEY ("EspecieId") REFERENCES "Especies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Citas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FechaCita" timestamp with time zone NOT NULL,
    "Motivo" character varying(250) NOT NULL,
    "Estado" character varying(50) NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "MascotaId" integer NOT NULL,
    "VeterinarioId" integer NOT NULL,
    CONSTRAINT "PK_Citas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Citas_Mascotas_MascotaId" FOREIGN KEY ("MascotaId") REFERENCES "Mascotas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Citas_Veterinarios_VeterinarioId" FOREIGN KEY ("VeterinarioId") REFERENCES "Veterinarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tratamientos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descripcion" character varying(500) NOT NULL,
    "Costo" numeric NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "CitaId" integer NOT NULL,
    CONSTRAINT "PK_Tratamientos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tratamientos_Citas_CitaId" FOREIGN KEY ("CitaId") REFERENCES "Citas" ("Id") ON DELETE CASCADE
);

INSERT INTO "Duenos" ("Id", "Activo", "Apellido", "Correo", "Direccion", "FechaCreacion", "Nombre", "Telefono")
VALUES (1, TRUE, 'Perez', 'juan@example.com', '', TIMESTAMPTZ '2026-06-12T03:43:44.377099Z', 'Juan', '123456789');
INSERT INTO "Duenos" ("Id", "Activo", "Apellido", "Correo", "Direccion", "FechaCreacion", "Nombre", "Telefono")
VALUES (2, TRUE, 'Gomez', 'maria@example.com', '', TIMESTAMPTZ '2026-06-12T03:43:44.377184Z', 'Maria', '987654321');
INSERT INTO "Duenos" ("Id", "Activo", "Apellido", "Correo", "Direccion", "FechaCreacion", "Nombre", "Telefono")
VALUES (3, TRUE, 'Ruiz', 'carlos@example.com', '', TIMESTAMPTZ '2026-06-12T03:43:44.377184Z', 'Carlos', '555555555');
INSERT INTO "Duenos" ("Id", "Activo", "Apellido", "Correo", "Direccion", "FechaCreacion", "Nombre", "Telefono")
VALUES (4, TRUE, 'Lopez', 'ana@example.com', '', TIMESTAMPTZ '2026-06-12T03:43:44.377184Z', 'Ana', '444444444');
INSERT INTO "Duenos" ("Id", "Activo", "Apellido", "Correo", "Direccion", "FechaCreacion", "Nombre", "Telefono")
VALUES (5, TRUE, 'Diaz', 'luis@example.com', '', TIMESTAMPTZ '2026-06-12T03:43:44.377184Z', 'Luis', '333333333');

INSERT INTO "Especies" ("Id", "Activo", "FechaCreacion", "Nombre")
VALUES (1, TRUE, TIMESTAMPTZ '2026-06-12T03:43:44.376553Z', 'Perro');
INSERT INTO "Especies" ("Id", "Activo", "FechaCreacion", "Nombre")
VALUES (2, TRUE, TIMESTAMPTZ '2026-06-12T03:43:44.376605Z', 'Gato');
INSERT INTO "Especies" ("Id", "Activo", "FechaCreacion", "Nombre")
VALUES (3, TRUE, TIMESTAMPTZ '2026-06-12T03:43:44.376605Z', 'Ave');
INSERT INTO "Especies" ("Id", "Activo", "FechaCreacion", "Nombre")
VALUES (4, TRUE, TIMESTAMPTZ '2026-06-12T03:43:44.376605Z', 'Roedor');
INSERT INTO "Especies" ("Id", "Activo", "FechaCreacion", "Nombre")
VALUES (5, TRUE, TIMESTAMPTZ '2026-06-12T03:43:44.376605Z', 'Reptil');

INSERT INTO "Veterinarios" ("Id", "Activo", "Apellido", "Especialidad", "FechaCreacion", "Nombre", "Telefono")
VALUES (1, TRUE, 'Sanchez', 'General', TIMESTAMPTZ '2026-06-12T03:43:44.377246Z', 'Dr. Roberto', '');
INSERT INTO "Veterinarios" ("Id", "Activo", "Apellido", "Especialidad", "FechaCreacion", "Nombre", "Telefono")
VALUES (2, TRUE, 'Martinez', 'Cirugía', TIMESTAMPTZ '2026-06-12T03:43:44.3773Z', 'Dra. Laura', '');
INSERT INTO "Veterinarios" ("Id", "Activo", "Apellido", "Especialidad", "FechaCreacion", "Nombre", "Telefono")
VALUES (3, TRUE, 'Ramirez', 'Dermatología', TIMESTAMPTZ '2026-06-12T03:43:44.3773Z', 'Dr. Pedro', '');
INSERT INTO "Veterinarios" ("Id", "Activo", "Apellido", "Especialidad", "FechaCreacion", "Nombre", "Telefono")
VALUES (4, TRUE, 'Herrera', 'Oftalmología', TIMESTAMPTZ '2026-06-12T03:43:44.3773Z', 'Dra. Sofia', '');
INSERT INTO "Veterinarios" ("Id", "Activo", "Apellido", "Especialidad", "FechaCreacion", "Nombre", "Telefono")
VALUES (5, TRUE, 'Torres', 'Traumatología', TIMESTAMPTZ '2026-06-12T03:43:44.3773Z', 'Dr. Miguel', '');

INSERT INTO "Mascotas" ("Id", "Activo", "DuenoId", "EspecieId", "FechaCreacion", "FechaNacimiento", "Nombre", "Peso")
VALUES (1, TRUE, 1, 1, TIMESTAMPTZ '2026-06-12T03:43:44.377341Z', TIMESTAMPTZ '2020-01-01T00:00:00Z', 'Rex', 15.5);
INSERT INTO "Mascotas" ("Id", "Activo", "DuenoId", "EspecieId", "FechaCreacion", "FechaNacimiento", "Nombre", "Peso")
VALUES (2, TRUE, 2, 2, TIMESTAMPTZ '2026-06-12T03:43:44.377433Z', TIMESTAMPTZ '2021-05-10T00:00:00Z', 'Miau', 4.2);
INSERT INTO "Mascotas" ("Id", "Activo", "DuenoId", "EspecieId", "FechaCreacion", "FechaNacimiento", "Nombre", "Peso")
VALUES (3, TRUE, 3, 3, TIMESTAMPTZ '2026-06-12T03:43:44.377434Z', TIMESTAMPTZ '2022-08-15T00:00:00Z', 'Piolin', 0.5);
INSERT INTO "Mascotas" ("Id", "Activo", "DuenoId", "EspecieId", "FechaCreacion", "FechaNacimiento", "Nombre", "Peso")
VALUES (4, TRUE, 4, 4, TIMESTAMPTZ '2026-06-12T03:43:44.377434Z', TIMESTAMPTZ '2023-02-20T00:00:00Z', 'Hams', 0.3);
INSERT INTO "Mascotas" ("Id", "Activo", "DuenoId", "EspecieId", "FechaCreacion", "FechaNacimiento", "Nombre", "Peso")
VALUES (5, TRUE, 5, 5, TIMESTAMPTZ '2026-06-12T03:43:44.377434Z', TIMESTAMPTZ '2019-11-30T00:00:00Z', 'Igu', 2.1);

INSERT INTO "Citas" ("Id", "Activo", "Estado", "FechaCita", "FechaCreacion", "MascotaId", "Motivo", "VeterinarioId")
VALUES (1, TRUE, 'Programada', TIMESTAMPTZ '2026-06-13T03:43:44.37749Z', TIMESTAMPTZ '2026-06-12T03:43:44.377477Z', 1, 'Control anual', 1);
INSERT INTO "Citas" ("Id", "Activo", "Estado", "FechaCita", "FechaCreacion", "MascotaId", "Motivo", "VeterinarioId")
VALUES (2, TRUE, 'Programada', TIMESTAMPTZ '2026-06-14T03:43:44.377547Z', TIMESTAMPTZ '2026-06-12T03:43:44.377547Z', 2, 'Vacunación', 2);
INSERT INTO "Citas" ("Id", "Activo", "Estado", "FechaCita", "FechaCreacion", "MascotaId", "Motivo", "VeterinarioId")
VALUES (3, TRUE, 'Programada', TIMESTAMPTZ '2026-06-15T03:43:44.377548Z', TIMESTAMPTZ '2026-06-12T03:43:44.377548Z', 3, 'Revisión ala', 3);
INSERT INTO "Citas" ("Id", "Activo", "Estado", "FechaCita", "FechaCreacion", "MascotaId", "Motivo", "VeterinarioId")
VALUES (4, TRUE, 'Programada', TIMESTAMPTZ '2026-06-16T03:43:44.377548Z', TIMESTAMPTZ '2026-06-12T03:43:44.377548Z', 4, 'Corte de uñas', 4);
INSERT INTO "Citas" ("Id", "Activo", "Estado", "FechaCita", "FechaCreacion", "MascotaId", "Motivo", "VeterinarioId")
VALUES (5, TRUE, 'Programada', TIMESTAMPTZ '2026-06-17T03:43:44.377548Z', TIMESTAMPTZ '2026-06-12T03:43:44.377548Z', 5, 'Chequeo piel', 5);

INSERT INTO "Tratamientos" ("Id", "Activo", "CitaId", "Costo", "Descripcion", "FechaCreacion")
VALUES (1, TRUE, 1, 30.0, 'Revisión general completa', TIMESTAMPTZ '2026-06-12T03:43:44.377582Z');
INSERT INTO "Tratamientos" ("Id", "Activo", "CitaId", "Costo", "Descripcion", "FechaCreacion")
VALUES (2, TRUE, 2, 25.5, 'Aplicación vacuna antirrábica', TIMESTAMPTZ '2026-06-12T03:43:44.377636Z');
INSERT INTO "Tratamientos" ("Id", "Activo", "CitaId", "Costo", "Descripcion", "FechaCreacion")
VALUES (3, TRUE, 3, 15.0, 'Curación ala', TIMESTAMPTZ '2026-06-12T03:43:44.377636Z');
INSERT INTO "Tratamientos" ("Id", "Activo", "CitaId", "Costo", "Descripcion", "FechaCreacion")
VALUES (4, TRUE, 4, 10.0, 'Corte de uñas', TIMESTAMPTZ '2026-06-12T03:43:44.377636Z');
INSERT INTO "Tratamientos" ("Id", "Activo", "CitaId", "Costo", "Descripcion", "FechaCreacion")
VALUES (5, TRUE, 5, 20.0, 'Limpieza de escamas', TIMESTAMPTZ '2026-06-12T03:43:44.377636Z');

CREATE INDEX "IX_Citas_MascotaId" ON "Citas" ("MascotaId");

CREATE INDEX "IX_Citas_VeterinarioId" ON "Citas" ("VeterinarioId");

CREATE INDEX "IX_Mascotas_DuenoId" ON "Mascotas" ("DuenoId");

CREATE INDEX "IX_Mascotas_EspecieId" ON "Mascotas" ("EspecieId");

CREATE INDEX "IX_Tratamientos_CitaId" ON "Tratamientos" ("CitaId");

SELECT setval(
    pg_get_serial_sequence('"Duenos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Duenos") + 1,
        nextval(pg_get_serial_sequence('"Duenos"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Especies"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Especies") + 1,
        nextval(pg_get_serial_sequence('"Especies"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Veterinarios"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Veterinarios") + 1,
        nextval(pg_get_serial_sequence('"Veterinarios"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Mascotas"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Mascotas") + 1,
        nextval(pg_get_serial_sequence('"Mascotas"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Citas"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Citas") + 1,
        nextval(pg_get_serial_sequence('"Citas"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Tratamientos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Tratamientos") + 1,
        nextval(pg_get_serial_sequence('"Tratamientos"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260612034345_InitialCreate', '10.0.9');

COMMIT;

