// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeterinariaApp.Data;

#nullable disable

namespace VeterinariaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612034345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeterinariaApp.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MascotaId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Citas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Estado = "Programada",
                            FechaCita = new DateTime(2026, 6, 13, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(4907),
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(4770),
                            MascotaId = 1,
                            Motivo = "Control anual",
                            VeterinarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Estado = "Programada",
                            FechaCita = new DateTime(2026, 6, 14, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(5476),
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(5476),
                            MascotaId = 2,
                            Motivo = "Vacunación",
                            VeterinarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Estado = "Programada",
                            FechaCita = new DateTime(2026, 6, 15, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(5481),
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(5481),
                            MascotaId = 3,
                            Motivo = "Revisión ala",
                            VeterinarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Estado = "Programada",
                            FechaCita = new DateTime(2026, 6, 16, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(5483),
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(5482),
                            MascotaId = 4,
                            Motivo = "Corte de uñas",
                            VeterinarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Estado = "Programada",
                            FechaCita = new DateTime(2026, 6, 17, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(5484),
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(5484),
                            MascotaId = 5,
                            Motivo = "Chequeo piel",
                            VeterinarioId = 5
                        });
                });

            modelBuilder.Entity("VeterinariaApp.Models.Dueno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Duenos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Perez",
                            Correo = "juan@example.com",
                            Direccion = "",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(995),
                            Nombre = "Juan",
                            Telefono = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellido = "Gomez",
                            Correo = "maria@example.com",
                            Direccion = "",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(1844),
                            Nombre = "Maria",
                            Telefono = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellido = "Ruiz",
                            Correo = "carlos@example.com",
                            Direccion = "",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(1845),
                            Nombre = "Carlos",
                            Telefono = "555555555"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellido = "Lopez",
                            Correo = "ana@example.com",
                            Direccion = "",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(1846),
                            Nombre = "Ana",
                            Telefono = "444444444"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellido = "Diaz",
                            Correo = "luis@example.com",
                            Direccion = "",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(1847),
                            Nombre = "Luis",
                            Telefono = "333333333"
                        });
                });

            modelBuilder.Entity("VeterinariaApp.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Especies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 376, DateTimeKind.Utc).AddTicks(5532),
                            Nombre = "Perro"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 376, DateTimeKind.Utc).AddTicks(6053),
                            Nombre = "Gato"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 376, DateTimeKind.Utc).AddTicks(6054),
                            Nombre = "Ave"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 376, DateTimeKind.Utc).AddTicks(6054),
                            Nombre = "Roedor"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 376, DateTimeKind.Utc).AddTicks(6055),
                            Nombre = "Reptil"
                        });
                });

            modelBuilder.Entity("VeterinariaApp.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DuenoId")
                        .HasColumnType("integer");

                    b.Property<int>("EspecieId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DuenoId");

                    b.HasIndex("EspecieId");

                    b.ToTable("Mascotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            DuenoId = 1,
                            EspecieId = 1,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(3413),
                            FechaNacimiento = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Rex",
                            Peso = 15.5m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            DuenoId = 2,
                            EspecieId = 2,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(4339),
                            FechaNacimiento = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Miau",
                            Peso = 4.2m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            DuenoId = 3,
                            EspecieId = 3,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(4343),
                            FechaNacimiento = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Piolin",
                            Peso = 0.5m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            DuenoId = 4,
                            EspecieId = 4,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(4344),
                            FechaNacimiento = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Hams",
                            Peso = 0.3m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            DuenoId = 5,
                            EspecieId = 5,
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(4345),
                            FechaNacimiento = new DateTime(2019, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Igu",
                            Peso = 2.1m
                        });
                });

            modelBuilder.Entity("VeterinariaApp.Models.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CitaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.ToTable("Tratamientos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CitaId = 1,
                            Costo = 30.00m,
                            Descripcion = "Revisión general completa",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(5829)
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CitaId = 2,
                            Costo = 25.50m,
                            Descripcion = "Aplicación vacuna antirrábica",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(6360)
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CitaId = 3,
                            Costo = 15.00m,
                            Descripcion = "Curación ala",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(6362)
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CitaId = 4,
                            Costo = 10.00m,
                            Descripcion = "Corte de uñas",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(6363)
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CitaId = 5,
                            Costo = 20.00m,
                            Descripcion = "Limpieza de escamas",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(6364)
                        });
                });

            modelBuilder.Entity("VeterinariaApp.Models.Veterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Veterinarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Sanchez",
                            Especialidad = "General",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(2461),
                            Nombre = "Dr. Roberto",
                            Telefono = ""
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellido = "Martinez",
                            Especialidad = "Cirugía",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(3004),
                            Nombre = "Dra. Laura",
                            Telefono = ""
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellido = "Ramirez",
                            Especialidad = "Dermatología",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(3005),
                            Nombre = "Dr. Pedro",
                            Telefono = ""
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellido = "Herrera",
                            Especialidad = "Oftalmología",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(3006),
                            Nombre = "Dra. Sofia",
                            Telefono = ""
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellido = "Torres",
                            Especialidad = "Traumatología",
                            FechaCreacion = new DateTime(2026, 6, 12, 3, 43, 44, 377, DateTimeKind.Utc).AddTicks(3007),
                            Nombre = "Dr. Miguel",
                            Telefono = ""
                        });
                });

            modelBuilder.Entity("VeterinariaApp.Models.Cita", b =>
                {
                    b.HasOne("VeterinariaApp.Models.Mascota", "Mascota")
                        .WithMany("Citas")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApp.Models.Veterinario", "Veterinario")
                        .WithMany("Citas")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VeterinariaApp.Models.Mascota", b =>
                {
                    b.HasOne("VeterinariaApp.Models.Dueno", "Dueno")
                        .WithMany("Mascotas")
                        .HasForeignKey("DuenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinariaApp.Models.Especie", "Especie")
                        .WithMany("Mascotas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueno");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("VeterinariaApp.Models.Tratamiento", b =>
                {
                    b.HasOne("VeterinariaApp.Models.Cita", "Cita")
                        .WithMany("Tratamientos")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("VeterinariaApp.Models.Cita", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("VeterinariaApp.Models.Dueno", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("VeterinariaApp.Models.Especie", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("VeterinariaApp.Models.Mascota", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("VeterinariaApp.Models.Veterinario", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
